/*

Project Euler problem 2

Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not 
exceed four million.

*/

import java.util.Scanner;

public class PB2{
	public static void main(String[] args) {
		int sum = 0 ;
		int n1 = 1;
		int n2 = 2;
		while ( n1 < 4000000 ) {
			if ( (n1 & 1) == 0 ){    // n1 % 2 == 0
				sum += n1;
			}
			n2=n1+n2;                // n2 = sum
			n1=n2-n1;                // n1 = the old value of n2
		}
		System.out.println(sum);
	}
}